In [1]:
import numpy as np
import pandas as pd


df = pd.read_csv("../data/USvideos.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  object
 1   trending_date           40949 non-null  object
 2   title                   40949 non-null  object
 3   channel_title           40949 non-null  object
 4   category_id             40949 non-null  int64
 5   publish_time            40949 non-null  object
 6   tags                    40949 non-null  object
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  thumbnail_link          40949 non-null  object
 12  comments_disabled       40949 non-null  bool
 13  ratings_disabled        40949 non-null  bool
 14  video_error_or_removed  40949 non-null  bool
 15  description             40379 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.2+ MB

In [2]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [3]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [4]:
df.drop(df.columns[[0,1,5,7,8,9,10,11,12,13,14]], axis = 1, inplace = True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          40949 non-null  object
 1   channel_title  40949 non-null  object
 2   category_id    40949 non-null  int64
 3   tags           40949 non-null  object
 4   description    40379 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.6+ MB

In [6]:
#remove rows with no values
rows_with_nan = [index for index, row in df.iterrows() if row.isnull().any()]

In [7]:
print("Rows with NaN: ", len(rows_with_nan))
df.drop(rows_with_nan, inplace = True)

Rows with NaN:  570

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40379 entries, 0 to 40948
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          40379 non-null  object
 1   channel_title  40379 non-null  object
 2   category_id    40379 non-null  int64
 3   tags           40379 non-null  object
 4   description    40379 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.8+ MB

In [9]:
#remove stopwords from df
from nltk.corpus import stopwords

stop = stopwords.words("english")

In [10]:
#clean puntuation
def clean_punct(x):
    try:
        x = x.str.replace('"','')
        x = x.str.replace('[^\w\s]',' ')
    except:
        pass
    return x

df_no_punctuation = df.apply(clean_punct)

<ipython-input-10-207da87db145>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  x = x.str.replace('[^\w\s]',' ')

In [11]:
df_no_punctuation.head()

,title,channel_title,category_id,tags,description
0,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,SHANtell martin,SHANTELL S CHANNEL https www youtube com s...
1,The Trump Presidency Last Week Tonight with J...,LastWeekTonight,24,last week tonight trump presidency last week t...,One year after the presidential election John...
2,Racist Superman Rudy Mancuso King Bach Le...,Rudy Mancuso,23,racist superman rudy mancuso king bach racist ...,WATCH MY PREVIOUS VIDEO n nSUBSCRIBE http...
3,Nickelback Lyrics Real or Fake,Good Mythical Morning,24,rhett and link gmm good mythical morning rhett...,Today we find out if Link is a Nickelback amat...
4,I Dare You GOING BALD,nigahiga,24,ryan higa higatv nigahiga i dare you idy rhpc ...,I know it s been a while since we did this sho...

In [12]:
#prep for removing stopwords by lowercase/split
df_lower = df_no_punctuation.apply(lambda x: x.astype(str).str.lower().str.split())

In [13]:
df_lower.head()

,title,channel_title,category_id,tags,description
0,"[we, want, to, talk, about, our, marriage]",[caseyneistat],[22],"[shantell, martin]","[shantell, s, channel, https, www, youtube, co..."
1,"[the, trump, presidency, last, week, tonight, ...",[lastweektonight],[24],"[last, week, tonight, trump, presidency, last,...","[one, year, after, the, presidential, election..."
2,"[racist, superman, rudy, mancuso, king, bach, ...","[rudy, mancuso]",[23],"[racist, superman, rudy, mancuso, king, bach, ...","[watch, my, previous, video, n, nsubscribe, ht..."
3,"[nickelback, lyrics, real, or, fake]","[good, mythical, morning]",[24],"[rhett, and, link, gmm, good, mythical, mornin...","[today, we, find, out, if, link, is, a, nickel..."
4,"[i, dare, you, going, bald]",[nigahiga],[24],"[ryan, higa, higatv, nigahiga, i, dare, you, i...","[i, know, it, s, been, a, while, since, we, di..."

In [14]:
#remove all stopwords
df_lower['title'] = df_lower['title'].apply(lambda x: [item for item in x if item not in stop])
df_lower['channel_title'] = df_lower['channel_title'].apply(lambda x: [item for item in x if item not in stop])
df_lower['tags'] = df_lower['tags'].apply(lambda x: [item for item in x if item not in stop])
df_lower['description'] = df_lower['description'].apply(lambda x: [item for item in x if item not in stop])

In [15]:
df_lower.head()

,title,channel_title,category_id,tags,description
0,"[want, talk, marriage]",[caseyneistat],[22],"[shantell, martin]","[shantell, channel, https, www, youtube, com, ..."
1,"[trump, presidency, last, week, tonight, john,...",[lastweektonight],[24],"[last, week, tonight, trump, presidency, last,...","[one, year, presidential, election, john, oliv..."
2,"[racist, superman, rudy, mancuso, king, bach, ...","[rudy, mancuso]",[23],"[racist, superman, rudy, mancuso, king, bach, ...","[watch, previous, video, n, nsubscribe, https,..."
3,"[nickelback, lyrics, real, fake]","[good, mythical, morning]",[24],"[rhett, link, gmm, good, mythical, morning, rh...","[today, find, link, nickelback, amateur, secre..."
4,"[dare, going, bald]",[nigahiga],[24],"[ryan, higa, higatv, nigahiga, dare, idy, rhpc...","[know, since, show, back, might, best, episode..."

In [16]:
df_final = df_lower.apply(lambda x: x.astype(str).str.replace(',',';'))
df_final = df_final.apply(lambda x: x.astype(str).str.replace('\'',''))
df_final = df_final.apply(lambda x: x.astype(str).str.replace('[',''))
df_final = df_final.apply(lambda x: x.astype(str).str.replace(']',''))

<ipython-input-16-85d7407676f7>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df_final = df_final.apply(lambda x: x.astype(str).str.replace('[',''))
<ipython-input-16-85d7407676f7>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df_final = df_final.apply(lambda x: x.astype(str).str.replace(']',''))

In [17]:
df_final.head()

,title,channel_title,category_id,tags,description
0,want; talk; marriage,caseyneistat,22,shantell; martin,shantell; channel; https; www; youtube; com; s...
1,trump; presidency; last; week; tonight; john; ...,lastweektonight,24,last; week; tonight; trump; presidency; last; ...,one; year; presidential; election; john; olive...
2,racist; superman; rudy; mancuso; king; bach; l...,rudy; mancuso,23,racist; superman; rudy; mancuso; king; bach; r...,watch; previous; video; n; nsubscribe; https; ...
3,nickelback; lyrics; real; fake,good; mythical; morning,24,rhett; link; gmm; good; mythical; morning; rhe...,today; find; link; nickelback; amateur; secret...
4,dare; going; bald,nigahiga,24,ryan; higa; higatv; nigahiga; dare; idy; rhpc;...,know; since; show; back; might; best; episode;...

In [18]:
df_final.to_csv("US_video_cleaned.csv")